### PR TITLE
Move from unsigned cookies to short lived signed cookies 

### PR DESCRIPTION
**Pull request by feralbob**
Following some of the discussion in https://github.com/w3c/webauthn/issues/1856

### CODE REVIEW

**Comment by feralbob** [comment]
Likely needs some tests but not sure of the best way to go about testing this effectively.

**Comment by crafterm** [comment]
@feralbob great work, I also needed similar changes in this PR to get things working too, particularly making the cookie values a JSON-ified String type rather than a structured type - or by using the session instead of cookies (which works and does accept a structured value) - otherwise the cookie value was coming back as empty in the registration request and the register, etc method couldn't find the challenge.

@troya2 mate does this PR need any further work to merge in, happy to contribute?

**Comment by feralbob** [comment]
@crafterm - I haven't heard anything from @troya2 since my early discussions/pairing with him to get the gem working.

Based on some of the discussion in https://github.com/w3c/webauthn/issues/1856 I'm still not sure this is the best approach.  I'd be ok with it back in the session, so the client didn't have access to things it didn't need.

Happy to chat more about this and how to test on devices if that's useful. Also wondering about best way to sanitize the inputs used to create the model.

**Comment by troya2** [comment]
Thank you!

**Pull request merged**
